spring:
  application:
    name: api-gateway

server:
  port: 8000

# Service Discovery configuration
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http:localhost:8761/eureka}

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    hello-world:
      path: /hello-world/**
      serviceId: hello-world
      stripPrefix: false

  endpoints:
    trace:
      sensitive: false

  ribbon:
    eureka:
      enabled: false