server:
  port: 8000

# Service Discovery configuration
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    hello-world:
      path: /hello-world/**
      serviceId: hello-world
      strip-prefix: false

  endpoints:
    trace:
      sensitive: false

  ribbon:
    eureka:
      enabled: false